on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Deploy to Azure'
      run: |
        ng run cv:deploy
